### ISSUE TITLE
I am working on a awesome-python-htmx, seeking your feedback

### ISSUE THREAD

**Issue by benjamin-kirkbride** [bensi94/Django-Requests-Tracker#7]
A few of us at PyCon this year got together and brainstormed a new Web Stack that we are calling PyHAT (Python, htmx, ASGI, TailwindCSS). The first thing we set out to do is create awesome-python-htmx; a collection of active tools/libraries/projects in that space.

Your project seems like an obvious thing to include, so I did. I'd appreciate your feedback if you have any on it's inclusion.

In addition to that, if you could also participate in PyHAT-stack/awesome-python-htmx#1 that would be greatly appreciated! I'd be particularly interested to hear how your experience shipping something using Django and HTMX was.

**Comment by bensi94** [comment]
Hi Benjamin. It looks like I missed this a few weeks ago. 

I'm glad that you decided to include the project in your awesome list and your PyHAT idea sounds really exciting. As far as I know, I think me and my place of work are the only users of this project. I have not really done anything to promote it elsewhere, but I think it has good potential and could be beneficial to a lot of people, it has at least been for me.

I will gladly write a few words about my project to the [PyHAT-Introductions discussion](https://github.com/PyHAT-stack/awesome-python-htmx/discussions/2).
