### ISSUE TITLE
`Django-Request-Tracker` breaks on `psycopg3`

### ISSUE THREAD

**Issue by AlTosterino** [bensi94/Django-Requests-Tracker#8]
Hey!

We are trying to switch to `psycopg 3.1.10` using `django-ninja 0.22.2, Django 4.2.4, requests-tracker 0.3.2`. Unfortunately, `requests-tracker` breaks with `psycopg > 2`

Stack trace:
```shell
  File "/Users/Tosuto/PycharmProjects/project/.venv/lib/python3.11/site-packages/debug_toolbar/panels/sql/tracking.py", line 177, in _record
    return method(sql, params)
           │      │    └ ('param',)
           │      └ 'SELECT "authentication_usermodel"."password", "authentication_usermodel"."last_login", "authentication_usermodel"."...
           └ <bound method CursorDebugWrapper.execute of <debug_toolbar.panels.sql.tracking.patch_cursor_wrapper_with_mixin.<locals>.DjDTC...
  File "/Users/Tosuto/PycharmProjects/project/.venv/lib/python3.11/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
                           │    └ ('param',)
                           └ 'SELECT "authentication_usermodel"."password", "authentication_usermodel"."last_login", "authentication_usermodel"."...
  File "/Users/Tosuto/PycharmProjects/ts-backend/.venv/lib/python3.11/site-packages/requests_tracker/sql/sql_hook.py", line 34, in execute
    return sql_tracker.record(
           │           └ <function SQLTracker.record at 0x104fdc040>
           └ <requests_tracker.sql.sql_tracker.SQLTracker object at 0x106744d90>
  File "/Users/Tosuto/PycharmProjects/project/.venv/lib/python3.11/site-packages/requests_tracker/sql/sql_tracker.py", line 239, in record
    initial_conn_status = conn.status
                          └ <psycopg.Connection [IDLE] (host=localhost user=user database=database) at 0x106729c90>

```
Any plan to support `psycopg3`, or should this project be pinned to support only ≤ 3?

Thanks in advance.

**Comment by bensi94** [comment]
Hi @AlTosterino sorry for the late response. I'm glad you're using Django-Request-Tracker and thanks for pointing this out, I did not know this.

I will look into this on the weekend and hopefully, it's an easy fix.

**Comment by AlTosterino** [comment]
@bensi94 Hey! Did you have a chance to look at this?

**Comment by bensi94** [comment]
Hey @AlTosterino! Thanks for pinging me, I kind of forgot about this sorry. But I'm working on this now, I've already merge a small update for dependencies to get the project back on track and hopefully I will finish the `psycopg3` part later this week.

**Comment by bensi94** [comment]
Hey @AlTosterino! A new version of Django Requests Tracker, [version 0.3.3](https://pypi.org/project/requests-tracker/0.3.3/) should now handle `psycopg3` correctly.

**Comment by AlTosterino** [comment]
Thanks you so much @bensi94
